### ISSUE TITLE
Alias complex Structure calls for vectorization

### ISSUE THREAD

**Issue by JPietrzykTUD** [MorphStore/Engine#12]
For ease of use we should alias static member functions from partial specialized helper structs.
Example:
```
template< typename T >
struct add_helper {
   static inline T apply( T a, T b ) { 
      return a + b;
   }
};
```
This is called like that:
```
#include <iostream>
int main( void ) {
   std::cout << add_helper< int >::apply( 3 , 4 ) << "\n";
   return 0;
}
```

Another approach would be to use `operator()` as a functor:
```
template< typename T >
struct add {
   inline T operator( )( T a, T b ) { 
      return a + b;
   }
};
```
This can be called like that:
```
#include <iostream>
int main( void ) {
   std::cout << add< int >{}( 3, 4 ) << "\n";
   return 0;
}
```

Downside: We need an instance of the helper struct `add`. This may lead to copying this pointers and so on.

Third approach:
```
#include <functional>
template< typename T >
struct add_helper {
   static inline T apply( T a, T b ) { 
      return a + b;
   }
};
template< typename T >
std::function< T ( T, T ) > add = add_helper< T >::apply;
```
This somehow combines the other approaches:
```
#include <iostream>
int main( void ) {
   std::cout << add< int >( 3, 4 ) << "\n";
   return 0;
}
```

Unfortunately I see the forest for the trees when it comes to apply approach 3 into existing multi-template vector code (e.g.: include/vector/simd/sse/primitives/io_sse.h) .

Help would be highly appreciated.

**Comment by the-monster** [comment]
Two coments about this:

1. It's enough if the load-function takes a void*. This takes away the template argument in the parameter, which we do not need anyway, i.e. we do not need to know which type our data has at this point (that would be too late anyway).
So the third approach would look something like this:
~~~{.cpp}
...
load( void const * p_DataPtr) {...}
...
template<typename T, int IOGranularity>
std::function< sse<v128<T>> (void const *)> load = io<sse<v128<T>>,iov::UNALIGNEDX, IOGranularity>::load;
~~~
-> Surprisingly this compiles :-)

2. We somehow need to know the iov (input-output-variant?) to choose the right io (with the according load-function). This is not possible with the example above, where we have to guess which iov we need.
A suggestion for restructuring this is to put the iov into the load-function (as a parameter?) instead of the struct, i.e. make one big struct with many (overloaded) load-functions. 
We might have to instantiate it in this case, which hopefully does not cost too much performance...but it shouldn't since we only need one instance.

Any comments about this? It is quite mind twisting to write down the according code.

**Comment by JPietrzykTUD** [comment]
Iff instantiating volatile helper structs is an option, imho a "normal" functor would be the best alternative:
```
template<typename T, int IOGranularity>
   struct load<sse<v128<T>>,iov::UNALIGNEDX, IOGranularity> {
      template< typename U = T, typename std::enable_if< std::is_integral< U >::value, int >::type = 0 >
      MSV_CXX_ATTRIBUTE_INLINE
      typename sse< v128< U > >::vector_t
      operator()( U const * const p_DataPtr ) {
         trace( "[VECTOR] - Loading unaligned integer values into 128 Bit vector register using lddqu." );
         return _mm_lddqu_si128(reinterpret_cast<typename sse< v128< U > >::vector_t const *>(p_DataPtr));
      }
```

This would be called like that: 
```
typename sse< v128< uint64_t > >::vector_t b =
      load< sse< v128< uint64_t > >, iov::UNALIGNED, 128 >{}( data );

```

In general it's not clear to me, what the costs of this would be - i am just a bit curious wether the compiler can and will inline this beauty.

**Comment by alexKrauseTUD** [comment]
Resolved.
